name: Deploy Infra to Azure Cloud

on: 
  push:
    branches:
      - main

permissions:
  contents: read


jobs:
 build-Infra:
   runs-on: ubuntu-latest
   environment: production
   
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
   defaults:
      run:
        shell: bash
   
   steps:
     - name: Checkout Self
       uses: actions/checkout@v4
     - name: SetUp NodeJs
       uses: actions/setup-node@v4
       with:
         node-version: 20
     - name: Run Node Ci
       run: npm ci
     - name: Run Node Install
       run: npm install -f frontend/
     - name: Run Frontend
       run: |
         cd frontend
         npm i
     - name: Run backend
       run: |
        cd backend
        npm i
     - name: Install All Package
       run: |
         npm i && npm run install-backend && npm run install-frontend
     - name: Cache SonarQube packages
       uses: actions/cache@v4
       with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
     - name: Cache Maven packages
       uses: actions/cache@v4
       with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
     - name: Build and analyze
       env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
       run: |
          npx sonar-scanner \
            -Dsonar.projectKey=MavenApp \
            -Dsonar.host.url=http://20.109.40.150:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    

     - name: Setup Terraform 
       uses: hashicorp/setup-terraform@v3
       #with:
         #cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

     - name: Deploy Cloud Infra to Azure Cloud
       #if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
       env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       run: |
        terraform init -upgrade
        terraform destroy --auto-approve
        terraform validate
        terraform fmt 
        terraform plan
        terraform apply --auto-approve
        terraform show
        terraform destroy --auto-approve
